import  Head  from 'next/head'
import React, { ReactNode } from 'react'

type layoutProps= {
    title:string,
    children:ReactNode
}

export default function Layout(props:layoutProps) {
  return (
    <>
        <Head>
            <title>Simple Bank App | {props.title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.children}
    </>
  )
}
